title: My pathway documentation site
description: Notes, project documentation, and research materials
theme: just-the-docs

url: "https://isaacs07.github.io"
baseurl: "/sturdy-pancake"

aux_links:
  "View on GitHub":
    - "https://github.com/Isaacs07/sturdy-pancake"
